# https://qlty.sh/d/qlty-toml

config_version = "0"

exclude_patterns = [
  ".build/**",
  "public/**",
  "tests/Unit/Fixtures/**",
  "var/**",
]

test_patterns = [
  "tests/**/*Test.php",
]

[smells]
mode = "comment"

[[source]]
name = "default"
default = true

[[plugin]]
name = "actionlint"

[[plugin]]
name = "checkov"

[[plugin]]
name = "markdownlint"
mode = "comment"

[[plugin]]
name = "osv-scanner"

[[plugin]]
name = "ripgrep"
mode = "comment"

[[plugin]]
name = "trivy"
drivers = [
  "config",
  "fs-vuln",
]

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "yamllint"

[[ignore]]
rules = ["yamllint:document-start", "yamllint:line-length"]

[[ignore]]
rules = ["yamllint:truthy"]
file_patterns = [".github/workflows/**"]

[[ignore]]
rules = ["markdownlint:MD041", "markdownlint:MD033", "markdownlint:MD013"]
file_patterns = ["README.md"]
